package com.oose2016.bcigdem1.dots;

/**
 * Created by mbugrahanc on 9/21/16.
 */
public class Box {
    private int row;
    private int col;
    /**
     * Either "RED", "BLUE", or "NONE" to describe the owner of this box.
     */
    private String owner;

    public Box(int row, int col, String owner) {
        this.row = row;
        this.col = col;
        this.owner = owner;
    }

    public Box(int row, int col) {
        this.row = row;
        this.col = col;
        this.owner = "NONE";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Box box = (Box) o;

        return (row == box.row && col == box.col && owner.equals(box.owner));
    }

    /**
     * @return Unique hash code generated by "row, col, owner"
     */
    @Override
    public int hashCode() {
        String boxId = Integer.toString(row) + "," + Integer.toString(col) + "," + owner;
        return boxId.hashCode();
    }

}
