package com.oose2016.bcigdem1.dots;

/**
 * Generic line model used to track moves.
 */
public class Line {
    private final int row;
    private final int col;
    private final boolean filled;

    public Line(int row, int col, boolean filled) {
        this.row = row;
        this.col = col;
        this.filled = filled;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Line line = (Line) o;

        return (row == line.row && col == line.col && filled == line.filled);
    }

    /**
     * @return Unique hash code generated by "row, col, 1 or 0 depending on filled"
     */
    @Override
    public int hashCode() {
        String coordinates = Integer.toString(row) + "," + Integer.toString(col) + "," + (filled ? "1" : "0");
        return coordinates.hashCode();
    }

}